[tool.poetry]
name = "fastflix"
version = "4.0.0"
description = "Easy to use video encoder GUI"
authors = ["Chris Griffith <chris@cdgriffith.com>"]
license = "MIT"
include = ["fastflix/data/rotations/*.png", "fastflix/data/encoders/*.png", "fastflix/data/icon.ico", "fastflix/CHANGES"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
appdirs = "^1.4.4"
qtpy = "^1.9.0"
python-box = {version = "^5.1.1", extras = ["all"]}
requests = "^2.24.0"
reusables = "^0.9.5"
"ruamel.yaml" = "^0.16.10"
mistune = "^0.8.4"
coloredlogs = "^14.0"
psutil = "^5.7.2"
PySide2 = "^5.15.1"
colorama = "^0.4.4"
iso639-lang = "^0.0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
fastflix = 'fastflix.__main__:start_fastflix'

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.pytest_cache
  | _build
  | build
  | dist
  | venv
)/
'''
