name: Run code linter "black"

on:
  push:
    branches: [ master, develop, build, 3.0 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: sudo apt install python3-pip -y
    - run: pip3 install black
    - run: black --check
